all: increasea.bin indirectjump1.bin pushhl.bin test.bin gradient.bin cycle.bin

increasea.bin: increasea.xxd
	xxd -p -r increasea.xxd > increasea.bin

indirectjump1.bin: indirectjump1.xxd
	xxd -p -r indirectjump1.xxd > indirectjump1.bin

pushhl.bin: pushhl.xxd
	xxd -p -r pushhl.xxd > pushhl.bin

test.bin: test.xxd
	xxd -p -r test.xxd > test.bin

gradient.bin: gradient.xxd
	xxd -p -r gradient.xxd > gradient.bin

cycle.bin: cycle.xxd
	xxd -p -r cycle.xxd > cycle.bin
